namespace SlimResolution.Core.ResolutionSourceProcessing;

public delegate ResolutionSource CreateResolutionSource(object rootServiceProvider);
public delegate object AccessRootServiceProvider(ResolutionSource resolutionSource);